### PR TITLE
Resolve syncing conflicts from from-prod-live to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from from-prod-live to live.

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[4ec9e10](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/35/commits/4ec9e10647b752cc62b1eabb897ada3dc03c93eb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-3f1bc39f) |

<a id="3f1bc39f"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\x21i-s, target branch: HEAD, target branch commit: c67dbc8f346790f47411001e1363fc21f833346f, source commit: 4ec9e10647b752cc62b1eabb897ada3dc03c93eb.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C6%5C11%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201906111450108369-35%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U2CtClVo2bB0o0797Qycr%2F3ykJcgXgyP4ugDhTjb8sw%3D&st=2019-06-11T14%3A45%3A31Z&se=2019-07-12T14%3A50%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[a6f13c1](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/35/commits/a6f13c16a535acea279c0ddeca72f1f0d8a8ce4c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-12ebfb01) |

<a id="12ebfb01"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\5wdl-s, target branch: HEAD, target branch commit: c67dbc8f346790f47411001e1363fc21f833346f, source commit: a6f13c16a535acea279c0ddeca72f1f0d8a8ce4c.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C6%5C12%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201906121744463032-35%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4Z24QLN3CVHdlGy6p7cmhp3EonE%2B1fOCa3BzY%2F6CVac%3D&st=2019-06-12T17%3A40%3A41Z&se=2019-07-13T17%3A45%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
Docs Build status updates of commit _[13f2478](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/35/commits/13f24786ed39ca1c07eff2b73a1974c366e31cb8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-f0c6eb3a) |

<a id="f0c6eb3a"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\tkbo-s, target branch: HEAD, target branch commit: c67dbc8f346790f47411001e1363fc21f833346f, source commit: 13f24786ed39ca1c07eff2b73a1974c366e31cb8.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C6%5C19%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201906192118225951-35%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X6BDyEp%2FL8AD3Sc3VA%2FCIyEnpfiTrFOg4Q7HAI1vMqw%3D&st=2019-06-19T21%3A14%3A59Z&se=2019-07-20T21%3A19%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[f60fa42](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/35/commits/f60fa420bdc81db174e6168d3aeb11371e483162)_: 

:clock10: **Pending**: waiting for processors ([19](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 19 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[f60fa42](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/35/commits/f60fa420bdc81db174e6168d3aeb11371e483162)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-3664c956) |

<a id="3664c956"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\mob1-s, target branch: HEAD, target branch commit: c67dbc8f346790f47411001e1363fc21f833346f, source commit: f60fa420bdc81db174e6168d3aeb11371e483162.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C6%5C20%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201906202152142723-35%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ToI3oAj51XGTe3ap3%2BlBXBpd8%2B%2FwooSiwD0e5Daiu5A%3D&st=2019-06-20T21%3A48%3A14Z&se=2019-07-21T21%3A53%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[b8427ec](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/35/commits/b8427ec6fbacee08da1a580743c338524179d0cc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-9473b193) |

<a id="9473b193"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\stbt-s, target branch: HEAD, target branch commit: c67dbc8f346790f47411001e1363fc21f833346f, source commit: b8427ec6fbacee08da1a580743c338524179d0cc.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C6%5C25%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201906252212472551-35%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1foz%2B3slv10yXLcK04ibqvkCa8HaAfvIUpSnZZwzIQs%3D&st=2019-06-25T22%3A10%3A16Z&se=2019-07-26T22%3A15%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
Docs Build status updates of commit _[f8e8271](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/35/commits/f8e82714e9302fef13538a2c18d5f6e5c5e6522b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-0aac98e5) |

<a id="0aac98e5"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C6%5C26%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201906260413540320-35%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c9yM7QkQTuXsnxO08mZzKhy9DVxnXcUVepAnYmnU6zw%3D&st=2019-06-26T04%3A10%3A00Z&se=2019-07-27T04%3A15%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
