### PR TITLE
Resolve syncing conflicts from repo_sync_novalidation_staging_branch to staging-nometavalidation

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_novalidation_staging_branch to staging-nometavalidation.

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[cc0dd5e](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/cc0dd5e0cb0c88a059ccda2da31c2c03d409bde0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8d1791ba)

<a id="8d1791ba"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\wfkl-s, target branch: HEAD, target branch commit: e4c22e5a4b7b2046126fb36e103d38d476d703de, source commit: cc0dd5e0cb0c88a059ccda2da31c2c03d409bde0.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910090244423000-66%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ddzrFc0%2F2PJzmov9kr%2FGrYQTyHxiPPGjE7ZrEydkil8%3D&st=2019-10-09T02%3A40%3A17Z&se=2019-11-09T02%3A45%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[910dfaf](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/910dfafa931469eff627cbde43905d5e44266fd7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b974a698)

<a id="b974a698"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\jqx4-s, target branch: HEAD, target branch commit: e4c22e5a4b7b2046126fb36e103d38d476d703de, source commit: 910dfafa931469eff627cbde43905d5e44266fd7.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910090301551517-66%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wqQ6SfXEzRvBn%2F2Hq4k3ts9RQMDQYSwtuwl8TaKfDLo%3D&st=2019-10-09T02%3A58%3A01Z&se=2019-11-09T03%3A03%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[08dceef](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/08dceeff42390e6361d87f5d7cab8b6f3c40bb3e)_: 

:clock10: **Pending**: waiting for processors ([9](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[08dceef](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/08dceeff42390e6361d87f5d7cab8b6f3c40bb3e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4f01a3df)

<a id="4f01a3df"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\opb0-s, target branch: HEAD, target branch commit: e4c22e5a4b7b2046126fb36e103d38d476d703de, source commit: 08dceeff42390e6361d87f5d7cab8b6f3c40bb3e.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910091945376236-66%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xsbJLZugWS8q68TGDqR6OIf5G7t4JyQFkS1rL5XhV0w%3D&st=2019-10-09T19%3A50%3A55Z&se=2019-11-09T19%3A55%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
