### PR TITLE
prtest-nometavalidation -> master-nometavalidation

### PR DESCRIPTION
**Pull request by opse2esa**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[09baa08](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/15/commits/09baa0821cb80f32fb81ad83cd0fb98714207ef1)_: 

:clock10: **Full build**: the average full build time is _15 min(s) 15 sec(s)_, this is based on the last _2_ build(s) for this repository.

 :warning: **This is a FULL build** due to the 'stating-nometavalidation' branch being a new branch in Docs Build service and is still building, or there are build errors in 'stating-nometavalidation' branch so the cache for incremental build is not available. Normally no action is required on your part, but if the full build persists, please contact your repository admin to manually perform a full build on the 'stating-nometavalidation' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[09baa08](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/15/commits/09baa0821cb80f32fb81ad83cd0fb98714207ef1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[.github/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/.github/TestingPullRequest.md) | :white_check_mark:Succeeded | | |
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C10%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905100144288213-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ghS19DwlSLxqzBu3DDXYprWm%2FTBm5HzcdDvklOs7rAc%3D&st=2019-05-10T01%3A51%3A52Z&se=2019-06-10T01%3A56%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
Docs Build status updates of commit _[1b6b232](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/15/commits/1b6b232a0e720f868b421c46463791ec4eabc00d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C10%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905100317084762-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nVoBV6kDixpJqMEte1qmkBFRo3uQS1SOz6xNdyZWdME%3D&st=2019-05-10T03%3A16%3A30Z&se=2019-06-10T03%3A21%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[77306c1](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/15/commits/77306c1db3b53c1814878916f292030dfda054c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[developer/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/developer/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-developer-docs/testingpullrequest?branch=pr-en-us-15) | [Details](#user-content-06f904d2-c0bef07e) |
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | |

<a id="06f904d2-c0bef07e"></a>
### [developer/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/developer/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/../nonexisted1.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/../nonexisted2.md).`````
 - **Line 10**: **[Warning]** `````Invalid file link:(~/../nonexisted3.md).`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C10%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905100317581643-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Mm4WNac6nhxGWZsC2X6mdsovk3MO2pw7lCpHPRJXEWI%3D&st=2019-05-10T03%3A20%3A30Z&se=2019-06-10T03%3A25%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
Docs Build status updates of commit _[77306c1](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/15/commits/77306c1db3b53c1814878916f292030dfda054c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[developer/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/developer/TestingPullRequest.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/e2eppe-developer-docs/testingpullrequest?branch=pr-en-us-15) | [Details](#user-content-06f904d2-95f95200) |
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | |

<a id="06f904d2-95f95200"></a>
### [developer/TestingPullRequest.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/prtest-nometavalidation/developer/TestingPullRequest.md)
 - **[Warning]** `````Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by Docs platform, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.`````
 - **[Warning]** `````the value invalid_type is undefined for metadata content_type`````
 - **Line 8**: **[Warning]** `````Invalid file link:(~/../nonexisted1.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/../nonexisted2.md).`````
 - **Line 10**: **[Warning]** `````Invalid file link:(~/../nonexisted3.md).`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C10%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905100727018649-15%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OEt3JR65iil0vIbUsMCXne190uKCA4kRDDnC1O8xEFg%3D&st=2019-05-10T07%3A25%3A40Z&se=2019-06-10T07%3A30%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[90c8f38](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/15/commits/90c8f380cfb8129507232c6af11291334e84d560)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-330089ac) |

<a id="330089ac"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C23%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905230150577377-15%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yP30P%2BvTXQsqsice7ZtLjU6CR%2B%2FBJd0VKolQryvVzJo%3D&st=2019-05-23T01%3A54%3A45Z&se=2019-06-23T01%3A59%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
