### PR TITLE
Staging merger to pr

### PR DESCRIPTION
**Pull request by opse2esa**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[9e0ffeb](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/9e0ffebbf84e491189488a3d66679c098d36cdf1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-f2dcafc8) |

<a id="f2dcafc8"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905090741599124-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m1NJo9B0l4EwcQ%2FtUFJkPtz9feOttYcrYC%2F%2BNufFoIU%3D&st=2019-05-09T07%3A37%3A20Z&se=2019-06-09T07%3A42%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[164fdcb](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/164fdcb809d095bd30b0736e1eb23d5e7996dadb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-12b29c70) |

<a id="12b29c70"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905090800067393-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aSUnB%2F9oJqorlo85VbdULScz9RCx9YQxoPPHSPOMS7Y%3D&st=2019-05-09T07%3A56%3A09Z&se=2019-06-09T08%3A01%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
Docs Build status updates of commit _[f0af642](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/f0af6428fa7a453fc6e7c2f0eb89a000774ee21e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-c86ae8cb) |

<a id="c86ae8cb"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905090803037339-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4bydzDeuBEG4vaUr77iK8t4yer8hyM1jPSUNKyHmdFs%3D&st=2019-05-09T07%3A58%3A27Z&se=2019-06-09T08%3A03%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[029c081](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/029c0811b420129c3d55b25221f51f010d6c180f)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[029c081](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/029c0811b420129c3d55b25221f51f010d6c180f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-52e04e89) |

<a id="52e04e89"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905090812222534-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8dJ3x2uy%2F67vBnwxIDzlm5NFAGtLt%2FlEmQmkFfFpTlI%3D&st=2019-05-09T08%3A07%3A42Z&se=2019-06-09T08%3A12%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[0f98ba4](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/0f98ba4861bffcfe514d1fe72d7d71580bfff886)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[0f98ba4](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/0f98ba4861bffcfe514d1fe72d7d71580bfff886)_: 

:clock10: **Pending**: waiting for processors ([7](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by v-susu-zz** [comment]
Docs Build status updates of commit _[0f98ba4](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/9/commits/0f98ba4861bffcfe514d1fe72d7d71580bfff886)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-1f5376c4) |

<a id="1f5376c4"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905090824162765-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zzB4gdgPL%2BnJCmI8oxS4MfAsLxsu36a6q6dLSu2thB4%3D&st=2019-05-09T08%3A59%3A34Z&se=2019-06-09T09%3A04%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
