### PR TITLE
Resolve syncing conflicts from from-prod-staging to staging

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from from-prod-staging to staging.

### CODE REVIEW

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[0f19d59](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/0f19d597379b8e36f49554fa5ebeb337078e24e5)_: 

:clock10: **Pending**: waiting for processors ([24](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 24 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[0f19d59](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/0f19d597379b8e36f49554fa5ebeb337078e24e5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1a4a7243)

<a id="1a4a7243"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\ba2g-s, target branch: staging, target branch commit: c8bc51afab1f5edd65f53a017580d9c7dc7c68ec, source commit: 0f19d597379b8e36f49554fa5ebeb337078e24e5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C16%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C202007161823321744-106%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nOeZfC9KQYDJq4ZlxTn%2B5SZZtnhbZnSvCCWcvYBngGw%3D&st=2020-07-16T18%3A20%3A55Z&se=2020-08-16T18%3A25%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/e0c7d008-6e11-64fd-15cb-c80c2fa5b957?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd2** [comment]
Docs Build status updates of commit _[2d8f032](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/2d8f0329f55a1b8743de9066e66192d12411099c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1122d3fe)

<a id="1122d3fe"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\tuwi-s, target branch: staging, target branch commit: 151c0e5718c2f20e2d838772a655674d038e85a5, source commit: 2d8f0329f55a1b8743de9066e66192d12411099c.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C16%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C202007161912043076-106%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lrzKs3qrHx1k93XrbK0aRlMZEmD74vxVOdIjuALkdNM%3D&st=2020-07-16T19%3A07%3A51Z&se=2020-08-16T19%3A12%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/e0c7d008-6e11-64fd-15cb-c80c2fa5b957?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[d4e9d59](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/d4e9d59ca4accd31d9b48a87ae7e3536c074b234)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1125ca77)

<a id="1125ca77"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\e2h3-s, target branch: staging, target branch commit: 151c0e5718c2f20e2d838772a655674d038e85a5, source commit: d4e9d59ca4accd31d9b48a87ae7e3536c074b234.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C16%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C202007161936059392-106%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=74rkeyKQNFB1pCONkrfyh903WAACNNuMvCmHvL7tFUI%3D&st=2020-07-16T19%3A33%3A27Z&se=2020-08-16T19%3A38%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/e0c7d008-6e11-64fd-15cb-c80c2fa5b957?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[4625155](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/4625155832599d9d3d19eeebde588650395390e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/from-prod-staging/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/from-prod-staging/reference/5.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Enable-PSRemoting.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/from-prod-staging/reference/6/Microsoft.PowerShell.Core/Enable-PSRemoting.md) | :white_check_mark:Succeeded | |
[reference/7.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/from-prod-staging/reference/7.0/Microsoft.PowerShell.Core/Enable-PSRemoting.md) | :white_check_mark:Succeeded | |
[reference/7.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/from-prod-staging/reference/7.1/Microsoft.PowerShell.Core/Enable-PSRemoting.md) | :white_check_mark:Succeeded | |
[reference/docfx.json](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/from-prod-staging/reference/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C7%5C16%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C202007162130497741-106%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fYEsfI6pKGsNDcm2VBcMzEdMEqeEOQKY%2BGB5YBn0hmQ%3D&st=2020-07-16T21%3A37%3A27Z&se=2020-08-16T21%3A42%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://opportal-sandbox.azurewebsites.net/#/repos/e0c7d008-6e11-64fd-15cb-c80c2fa5b957?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
