### PR TITLE
Resolve syncing conflicts from from-prod-staging to staging

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from from-prod-staging to staging.

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[6abedc9](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/6abedc9cc08e028569f84c5fc3bcfd78f2359353)_: 

:clock10: **Pending**: waiting for processors ([12](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[6abedc9](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/6abedc9cc08e028569f84c5fc3bcfd78f2359353)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ce463a70)

<a id="ce463a70"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\owbu-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: 6abedc9cc08e028569f84c5fc3bcfd78f2359353.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C4%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910042331014799-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KbqMu656cioTLZ0iR572d37FSt7A4WahXRE34%2BJ7qnI%3D&st=2019-10-04T23%3A30%3A58Z&se=2019-11-04T23%3A35%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[02b7d02](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/02b7d0236796374f80a726c11d1da89ec20f00dd)_: 

:clock10: **Pending**: waiting for processors ([5](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[02b7d02](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/02b7d0236796374f80a726c11d1da89ec20f00dd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5b4f9747)

<a id="5b4f9747"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\jp1l-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: 02b7d0236796374f80a726c11d1da89ec20f00dd.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C6%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910062005194375-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aJGsLf4yPreCBhSNoliRh7hDknoEszE%2FzswBVgUtOmc%3D&st=2019-10-06T20%3A00%3A56Z&se=2019-11-06T20%3A05%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[5fdced0](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/5fdced02bd149d31c51167bf56d1cdc9d4efd7a5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7b8396d0)

<a id="7b8396d0"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\uwx2-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: 5fdced02bd149d31c51167bf56d1cdc9d4efd7a5.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C7%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910071520347144-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y8RpFj7DP0ZxpFQtc7Dp6y4FVa9ip4%2BgLBzRI6bj2aE%3D&st=2019-10-07T15%3A16%3A10Z&se=2019-11-07T15%3A21%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[f7af6a2](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/f7af6a2a4ec17d2904a1aabbb09771d6f7791e18)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-564bee47)

<a id="564bee47"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\fgbh-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: f7af6a2a4ec17d2904a1aabbb09771d6f7791e18.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C7%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910071745127383-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WTgYH2zRdFXc1wE93mHXO%2BnhwCS0sc6xnW4dZKwbBqA%3D&st=2019-10-07T17%3A44%3A39Z&se=2019-11-07T17%3A49%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[e6d5c85](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/e6d5c858b8514d22ee083d5d8927912e0ac4e02e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-836e569e)

<a id="836e569e"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\gkg4-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: e6d5c858b8514d22ee083d5d8927912e0ac4e02e.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C7%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910072036293424-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jlyos%2FUQ9ZJSXSLusIueqEiSZzGWzQ340GuJuCeozgM%3D&st=2019-10-07T20%3A32%3A59Z&se=2019-11-07T20%3A37%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[b971ba0](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/b971ba021dcbfea32d74526635db84d20d9f3021)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fa175ecb)

<a id="fa175ecb"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\kyvd-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: b971ba021dcbfea32d74526635db84d20d9f3021.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C8%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910080021047717-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MvPIop4qH%2F2RLtAlDzi0UPimmUHD3Ree2cYuhwQXmC0%3D&st=2019-10-08T00%3A17%3A11Z&se=2019-11-08T00%3A22%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[4b258c3](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/4b258c32ca16dd67d6990d41a01a783586cfd887)_: 

:clock10: **Pending**: waiting for processors ([13](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[4b258c3](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/4b258c32ca16dd67d6990d41a01a783586cfd887)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a55fc593)

<a id="a55fc593"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\3hru-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: 4b258c32ca16dd67d6990d41a01a783586cfd887.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C8%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910081559390697-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dzqTFHaOe7G9qYSkr689cVjwsl76u9w1GnnYe7JAnnY%3D&st=2019-10-08T16%3A02%3A05Z&se=2019-11-08T16%3A07%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[84e97df](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/84e97df64e5be130996094c90451e202b9aa5556)_: 

:clock10: **Pending**: waiting for processors ([22](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 22 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[84e97df](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/84e97df64e5be130996094c90451e202b9aa5556)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-70d9398c)

<a id="70d9398c"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\2roe-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: 84e97df64e5be130996094c90451e202b9aa5556.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C8%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910082004154993-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gXywFtRTbOKZSmVTqQWP2mOFARpDssyk4oWai6sz6Fo%3D&st=2019-10-08T20%3A01%3A01Z&se=2019-11-08T20%3A06%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[a0f2ddf](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/a0f2ddfd3f962e015c7a5119c41a97582b28c0c3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-47ab91c0)

<a id="47ab91c0"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\zjcc-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: a0f2ddfd3f962e015c7a5119c41a97582b28c0c3.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910090223544881-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bVanAf7Qut3Z7oFAVtMvzmQf3Flx%2BxJ15CCCucBM0N8%3D&st=2019-10-09T02%3A19%3A59Z&se=2019-11-09T02%3A24%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[74536d5](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/74536d557206a0e84abc03578d875f88f2fa9eff)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f7d72dfc)

<a id="f7d72dfc"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\dzy0-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: 74536d557206a0e84abc03578d875f88f2fa9eff.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910090231397547-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=81zRR%2Bgb%2F6y7WZiKM95wbACK8VbbEb%2Fcs3KqbWPGw0A%3D&st=2019-10-09T02%3A27%3A49Z&se=2019-11-09T02%3A32%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[74536d5](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/74536d557206a0e84abc03578d875f88f2fa9eff)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b12c8b4f)

<a id="b12c8b4f"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\vuny-s, target branch: HEAD, target branch commit: a94eba743252778c2c33f04960ab4fa238c5c318, source commit: 74536d557206a0e84abc03578d875f88f2fa9eff.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C10%5C9%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201910090240447233-65%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=703Tkl%2F9dSdnMWcxZ0cMJviu5RjvQ5qB5Jc9aOURxSs%3D&st=2019-10-09T02%3A36%3A45Z&se=2019-11-09T02%3A41%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
