### PR TITLE
Resolve syncing conflicts from from-prod-live to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from from-prod-live to live.

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[e894ed8](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/e894ed833cef57967cdaf002f8c883f66864e836)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-86f7ab19) |

<a id="86f7ab19"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\nga1-s, target branch: HEAD, target branch commit: 214a267e383ce741144776a818c800b1dd5d860f, source commit: e894ed833cef57967cdaf002f8c883f66864e836.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C25%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201908252142354868-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6MZPO4l70uyiwiYgdr5d1aQJmEi0fmH0CETlDFw0FFw%3D&st=2019-08-25T21%3A38%3A04Z&se=2019-09-25T21%3A43%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[a02ccbe](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/a02ccbeaa17c0e513d6c4a21b877c88ac7725458)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f43274c1)

<a id="f43274c1"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\v54f-s, target branch: HEAD, target branch commit: 214a267e383ce741144776a818c800b1dd5d860f, source commit: a02ccbeaa17c0e513d6c4a21b877c88ac7725458.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201908281720484070-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RmmDq%2Fi85UKS%2FU9Ptd4%2BpD7S5vmXg4U7636P4e4mi%2Fc%3D&st=2019-08-28T17%3A16%3A18Z&se=2019-09-28T17%3A21%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[02eed65](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/02eed65c526ef19cf952c2129f280bb5615bf0c8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c3131757)

<a id="c3131757"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\n4bm-s, target branch: HEAD, target branch commit: 214a267e383ce741144776a818c800b1dd5d860f, source commit: 02eed65c526ef19cf952c2129f280bb5615bf0c8.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C3%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201909031740334458-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cV3RoTQ7bhb%2FfxcDxwAiF1BfT2qd9VC4oefw%2BJwAo4s%3D&st=2019-09-03T17%3A36%3A27Z&se=2019-10-04T17%3A41%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[718f8e2](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/718f8e28777fd4140fc05ae52cf4fc428bca1f5d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-68b70321)

<a id="68b70321"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\d02t-s, target branch: HEAD, target branch commit: 214a267e383ce741144776a818c800b1dd5d860f, source commit: 718f8e28777fd4140fc05ae52cf4fc428bca1f5d.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C5%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201909052237075463-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qoa5UEybHVqT0e6R%2Bym57T%2BMc9kwY6shPcjg%2BIg2QAw%3D&st=2019-09-05T22%3A33%3A03Z&se=2019-10-06T22%3A38%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[d1ba596](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/d1ba596f9e0d4df9565601a70687a126d535c917)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-536c20ce)

<a id="536c20ce"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\5rqd-s, target branch: HEAD, target branch commit: 214a267e383ce741144776a818c800b1dd5d860f, source commit: d1ba596f9e0d4df9565601a70687a126d535c917.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C5%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201909052333234090-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U%2Bczbq75eREgY7y%2FUV9%2BsjNHGvbWTW53xBgiQ5oKZf4%3D&st=2019-09-05T23%3A29%3A18Z&se=2019-10-06T23%3A34%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[683be3f](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/683be3f15268f40704dd706644a714c425fe457e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8b89146d)

<a id="8b89146d"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\tgv3-s, target branch: HEAD, target branch commit: 214a267e383ce741144776a818c800b1dd5d860f, source commit: 683be3f15268f40704dd706644a714c425fe457e.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C6%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201909060053271626-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=S%2Fb%2BFOOxteGlmqbkuCJaj%2FMekAvxadpdri8NLreKG5E%3D&st=2019-09-06T00%3A49%3A22Z&se=2019-10-07T00%3A54%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[ffcc1c5](https://github.com/OPS-E2E-PPE/PowerShell-Docs/commits/ffcc1c55f5b3adc063353cb75f2a2183acc2234a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5700a877)

<a id="5700a877"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C9%5C6%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201909061450174690-61%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xetqKv573JTF2LA18T15TrSWtZURo4%2Fc5sFlvbZjAn0%3D&st=2019-09-06T14%3A47%3A00Z&se=2019-10-07T14%3A52%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
