### PR TITLE
Resolve syncing conflicts from repo_sync_novalidation_live_branch to live-nometavalidation

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_novalidation_live_branch to live-nometavalidation.

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[ed1a362](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/17/commits/ed1a362e42a513cb27867753b28ba607e0379b46)_: 

:clock10: **Pending**: waiting for processors ([6](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[ed1a362](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/17/commits/ed1a362e42a513cb27867753b28ba607e0379b46)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-e6818e95) |

<a id="e6818e95"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\syeo-s, target branch: HEAD, target branch commit: 74c62ea4d875275c78db1615e61b93bb057420a0, source commit: ed1a362e42a513cb27867753b28ba607e0379b46.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C15%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905150318468493-17%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Gi0pGdXXZrRmZSApc7SV9iLVDGuhihICwTLHys1Q6JI%3D&st=2019-05-15T03%3A24%3A54Z&se=2019-06-15T03%3A29%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
Docs Build status updates of commit _[d839b10](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/17/commits/d839b1023c004c29fb67c6069eb0796cada27344)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[]() | :x:Error | | [Details](#user-content-8d13fc4b) |

<a id="8d13fc4b"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-PPE/powershell-docs, working directory: W:\v3o5-s, target branch: HEAD, target branch commit: 74c62ea4d875275c78db1615e61b93bb057420a0, source commit: d839b1023c004c29fb67c6069eb0796cada27344.`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C16%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905160846591840-17%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LoeP46UdZoQ2pybHRexlTquQQXDxNoCOqxKsnvMAVaE%3D&st=2019-05-16T08%3A42%3A29Z&se=2019-06-16T08%3A47%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[071da38](https://github.com/OPS-E2E-PPE/PowerShell-Docs/pull/17/commits/071da383060616ef5e594ced41447147bafe8837)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-PPE/PowerShell-Docs/blob/repo_sync_novalidation_live_branch/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C5%5C17%5Ce0c7d008-6e11-64fd-15cb-c80c2fa5b957%5CPullRequest%5C201905170455410266-17%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WJOin%2FIcNH9Qfprnczmrv5dM0bpDzR%2F5pTI%2F60ajtDc%3D&st=2019-05-17T04%3A54%3A45Z&se=2019-06-17T04%3A59%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
